export const ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        LOGIN_OTP: '/auth/login-otp',
        REGISTER: '/auth/register',
        SEND_OTP: '/auth/send-otp',
        VERIFY_OTP: '/auth/verify-otp',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
        SAVE_STEP1_DATA: '/auth/step1-lead',
        STORE_SYNC_DATA: '/auth/store-sync-data',
    },
    VIDEOS: {
        UPLOAD: '/api/video/upload',
        LIST: '/api/video',
        LATEST: '/api/video/latest',
        BY_ID: (id: string) => `/api/video/${id}`,
        DELETE: (id: string) => `/api/video/${id}`,
    },
    PAYMENT: {
        VERIFY: '/api/video/verify-payment',
        RAZORPAY_ORDER: '/api/payment/order',
        RAZORPAY_VERIFY: '/api/payment/verify',
        RAZORPAY_ORDER_LANDING: '/api/payment/order-landing',
        RAZORPAY_VERIFY_LANDING: '/api/payment/verify-landing',
        RAZORPAY_ORDER_INFLUENCER: '/api/payment/order-registration-influencer',
        RAZORPAY_VERIFY_INFLUENCER: '/api/payment/verify-landing-influencer',
    },
    WATI: {
        WEBHOOK: '/api/wati/webhook',
    },
    INFLUENCER_LINKS: '/influencer-links',
    USERS: {
        LIST: '/api/users',
    },
    ADMIN: {
        BASE: '/admin',
        RECORDS: '/admin/records',
        UNPAID_USERS: '/admin/unpaid-users',
        STATS: '/admin/stats',
        CHARTS: '/admin/charts',
        INVOICE: (id: string) => `/admin/invoice/${id}`,
        MANUAL_PAYMENT: (id: string) => `/admin/users/${id}/payment`,
        SEND_THANKYOU_EMAIL: (id: string) => `/admin/users/${id}/send-thankyou-email`,
        CONTACT_LEADS: '/admin/contact-leads',
        CONTACT_LEADS_EXPORT: '/admin/contact-leads/export',
        CREATE_USER: '/admin/users',
        VERIFY_OTP: '/admin/verify-otp',
    }
};
